name: Generate F-Droid Database

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # End of each day

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Set up Python 3.11
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Dependencies
      run: pip install -r requirements.txt --require-hashes --no-deps
    - name: Make Version Directory
      run: |
        mkdir -p pages/v1
    - name: Sync F-Droid Database
      run: |
        # Sync the F-Droid database, needed to avoid CORS
        python sync.py
    - name: Copy F-Droid DB into Version
      run: |
        cp repository.json pages/v1/
    - name: Generate Popularity Database
      run: |
        # Generate the popular DB
        python create.py \
          -u "${{ secrets.F_DROID_DATABASE_URL }}" \
          -f "popular.json" \
          -gh "${{ secrets.GITHUB_TOKEN }}"
    - name: Copy Popular DB into Version
      run: |
        cp popular.json pages/v1/
    - name: Upload DB to Artifacts
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
      with:
        path: pages

  # Deployment job
  deploy:
    if: (github.event_name == 'push'
      && github.ref_name == 'main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
